#!/bin/bash

command=$2

GVT_PCI="0000:00:02.0"
GVT_GUID="f7050061-c57e-40a2-932b-6e87ff7d8e41"
MDEV_TYPE="i915-GVTg_V5_2" 
DOMAIN=win10
if [ $# -ge 3 ]; then
    if [ $1 = "$DOMAIN" -a $2 = "prepare" -a $3 = "begin" ]; then
        echo "$GVT_GUID" > "/sys/bus/pci/devices/$GVT_PCI/mdev_supported_types/$MDEV_TYPE/create"
    elif [ $1 = "$DOMAIN" -a $2 = "release" -a $3 = "end" ]; then
        echo 1 > /sys/bus/pci/devices/$GVT_PCI/$GVT_GUID/remove
    fi
fi

if [[ $command == "started" ]]; then
    systemctl set-property --runtime -- system.slice AllowedCPUs=0,4
    systemctl set-property --runtime -- user.slice AllowedCPUs=0,4
    systemctl set-property --runtime -- init.slice AllowedCPUs=0,4
elif [[ $command == "release" ]]; then
    systemctl set-property --runtime -- system.slice AllowedCPUs=0-7
    systemctl set-property --runtime -- user.slice AllowedCPUs=0-7
    systemctl set-property --runtime -- init.slice AllowedCPUs=0-7
fi
